# Generated by Django 4.1.5 on 2023-02-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
